
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 29 17:07:23 CET 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 27;
  public static final int READ = 8;
  public static final int IDENT = 3;
  public static final int RPAREN = 19;
  public static final int RBRACE = 10;
  public static final int CHAR = 5;
  public static final int SEMI = 12;
  public static final int LPAREN = 18;
  public static final int LBRACKET = 15;
  public static final int LBRACE = 9;
  public static final int RBRACKET = 16;
  public static final int SUB = 23;
  public static final int INC = 20;
  public static final int BOOLVALUE = 4;
  public static final int COMMA = 14;
  public static final int EOF = 0;
  public static final int NUMBER = 2;
  public static final int DIV = 26;
  public static final int ADD = 22;
  public static final int PROG = 6;
  public static final int DEC = 21;
  public static final int CONST = 11;
  public static final int PRINT = 7;
  public static final int error = 1;
  public static final int ASSIGN = 13;
  public static final int NEW = 24;
  public static final int MUL = 25;
  public static final int VOID = 17;
}

